- Jenkinsfile
This updates blazegraph-runner to version 1.3. Required for go-site/pipeline changes for https://github.com/geneontology/go-site/pull/601
> Bg runner fix test

- Jenkinsfile
This fixes the command that broke the master build yesterday.
> adding python 3, instead of just python to script

- Jenkinsfile
This is the new "iteration" setup.
> setting which groups to use for a shorter run

- Jenkinsfile
Eyeballing, it looks like we are getting the ontology products as intended with the image.
> Issue 76 use odk

- Jenkinsfile
Temporary master change to test paint group.
> set RESOURCE_GROUPS to just paint for testing

- Jenkinsfile
For https://github.com/geneontology/pipeline/issues/90
> Issue 90 set release date

- Jenkinsfile
Sorry about that. The file parsers now.
> bad groovy syntax fix

- Jenkinsfile
This just updates gaferencer to the latest version Jim released recently.
> updating gaferencer to newest update in pipeline

- Jenkinsfile
For https://github.com/geneontology/pipeline/issues/120
> remove downloader #120

- Jenkinsfile
Should point to go-stats-summary.json not go-stats.json
> Fix the -b parameter

- Jenkinsfile
I think we need to do some work to update to current master w/out messing up my changes. But otherwise, this is what we want.
> Dockerize megastep test

- Jenkinsfile
This is a new PR from my own fork. This should be what master looks like once we want to add dockerization to the mega-make step. The other branch `grouped_gaferencer_test` is tuned to be a test of dockerization, and not expected to be very mergable. 
As always, sorry about the formatting :(.
> Issue 115 dockerize megastep

- Jenkinsfile
@kltm can you just check the aggregated-summaries file will be downloaded in the correct folder ? I didn't checked your cd commands
> Update stats script to final version

- Jenkinsfile
This updates the Jenkins file in order for the next release to bootstrap the new set of stats.
> Update Jenkins for new stats

- Jenkinsfile
https://github.com/geneontology/pipeline/issues/200
> Issue 200 ontology override

- Jenkinsfile
> Issue 220 noctua gorules

- Jenkinsfile
Rename minerval ttl to gpad process output files to be nocatua_[group]-src.gpad
> rename minerva ttl to gpad output files to use -src

- Jenkinsfile
> Set option to trigger fix for geneontology/go-site#1668

- Jenkinsfile
This reverts commit 687186e69aba2cb268e0b72b2e67bbd83c9be2ed.
Fixes #255.
> Revert "Update blazegraph-runner version"

- Jenkinsfile
The ontology build needs this version to use a new feature in dosdp-tools.
> Update odkfull image.

- Jenkinsfile
Trying again to update ODK image. This one should have `scp` (see #258).
> Update odkfull image

- Jenkinsfile
Image version was updated in the ontology repo to access a new dosdp-tools feature.
> Update odkfull image to align with ontology repo

- Jenkinsfile
> For #1944 assigned-by reports

- Jenkinsfile
For #399.
Change on `snapshot`.
> Update snapshot Jenkinsfile for #399

- Jenkinsfile
For https://github.com/geneontology/pipeline/issues/399.
Change on `release`.
> Update release Jenkinsfile for #399

- Jenkinsfile
For https://github.com/geneontology/pipeline/issues/399.
Change on `go-raw-data`.
> Update go-raw-data Jenkinsfile for #399
